services:
  - type: web
    name: helphub-backend
    env: node
    buildCommand: |
      apt-get update && apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      npm install
      node scripts/downloadModels.js
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 